apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngnix-deployment
  labels:
    app: web
spec:
     replicas: 1
     selector:
       matchLabels:
         app: web
     template:
       metadata:
         labels:
          app: web
       spec:
        containers:
        - name: nginx
          image: nginx:1.14
          ports:
          - containerPort: 80
